### ISSUE TITLE
Confusion with `MiniTest` vs `Minitest` 

### ISSUE THREAD

**Issue by weshatheleopard** [assert-value/assert_value_ruby#8]
Getting an error: 

```
NameError: uninitialized constant AssertValueAssertion::MiniTest
Did you mean?  Minitest
    /mnt/var/git/dev/apps/utility_scrapers/.bundle/gems/ruby/3.1.0/gems/assert_value-1.5.5/lib/assert_value.rb:297:in `soft_fail'
```
 It happens here:
https://github.com/assert-value/assert_value_ruby/blob/f1734a497672709d81c5767da5d798617831c215/lib/assert_value.rb#L296-L297

But you already know that `MiniTest` is old and `Minitest` is new, as is written here:

https://github.com/assert-value/assert_value_ruby/blob/f1734a497672709d81c5767da5d798617831c215/lib/assert_value.rb#L8-L11

There's no `MiniTest` in new. Therefore, the code should be:

```
  case ASSERT_VALUE_TEST_FRAMEWORK
  when :new_minitest then failure = Minitest::Assertion.new(diff)
  when :old_minitest then failure = MiniTest::Assertion.new(diff)
  when :rspec_only then failure = diff
  else failure = Test::Unit::Failure.new(name, filter_backtrace(caller(0)), diff)
  end
```

**Comment by smetana** [comment]
Thank you for report and PR. Closed in 13530c1de4ad35fe7636a127c152348467930390

**Comment by weshatheleopard** [comment]
Would you mind updating the (minor) version and releasing to Rubygems?

**Comment by smetana** [comment]
I would like to add more tests since we did not catch the issue.
I will release new gem next week (never deploy on weekends :) ). Would you mind to install with
```
gem 'assert_value', :git => 'https://github.com/assert-value/assert_value_ruby.git'
```
until then?

**Comment by smetana** [comment]
1.5.6 has been published to Rubygems
